### ISSUE TITLE
Спринт 26.09.2018 25%

### ISSUE THREAD

**Issue by Shtandart** [Shtandart/Cource_Project#2]
- [x]  Исследовательская часть 

- [x] Схема БД

- [ ] ТЗ

**Comment by Shtandart** [comment]
Схема БД в доке Исследовательская часть.
[ИЧ КомаровДС.docx](https://github.com/Shtandart/Cource_Project/files/2417273/default.docx)
[ТЗБД Комаров Д.С. САПР.Б-51.docx](https://github.com/Shtandart/Cource_Project/files/2417274/-51.docx)

**Comment by wldmr-key** [comment]
Здесь замечания по исследовательской части (ТЗ - в отдельной задаче)
Вот тут такие фокусы **"легко получить нужную им информацию"** не проходят - здесь уже нужно описывать какую информацию и как нужно получать и передавать. То есть в этом документе описываются все процессы системы

Ты совершенно напрасно называешь представленную картинку концептуальной схемой - она ей не является. Понятно, почему?

**3.Перечень задач, подлежащих решению в процессе разработки** - это, действительно, те задачи, которые ты собираешься решить, закончив исследование?

**PostgreSQL может похвастаться** - теперь это называется обоснованием? ))
