### ISSUE TITLE
Доработка ТЗ

### ISSUE THREAD

**Issue by wldmr-key** [Shtandart/Cource_Project#3]
**2.2.Перечень объектов автоматизации (объектов), на которых предполагается её использовать** - это в каком же ГОСТе такие подразделы встречаются?

**3.1.Краткие сведения об объекте автоматизации** каким образом эти операции выполняются в настоящее время (я-то знаю, но в ТЗ следует это указать)

**4.1.Требования к структуре системы 
•	База данных, хранящая в себе расписание преподавателей, учебных групп и учебный план.** 
это все?

**заполнение БД уполномоченным человеком** - это будет один человек? И он будет работать непосредственно с БД?

**6.Состав и содержание работ по созданию (развитию) системы** - форму - ближе к ГОСТ

**Comment by Shtandart** [comment]
[ТЗБД Комаров Д.С. САПР.Б-51.docx](https://github.com/Shtandart/Cource_Project/files/2439302/-51.docx)
Пункт перечня объектов автоматизации убрал 
3.1 Расписал как операции для автоматизирования выглядят на данный момент.
4.1 Дополнил перечень информации, которая  хранится в БД.
Заполнение БД уполномоченным человеком - в плане самого расписания учебных групп и преподавателей - да. Так как есть уже готовое расписание в Excel и его уже кто-то составляет. Насчёт заполнения всякой информации, которая касается неучебных моментов уже другой вопрос, скорее всего нужны будут другие, те кто оповещает о них и выкладывает учебные пособия. (например, человека из учебной группы - старосту)
6. Чуть переделал в человеческий вид.

**Comment by wldmr-key** [comment]
ок, сойдет. Функции и требования по-прежнему расплывчаты - это может сыграть не в твою пользу, как исполнителя
