### ISSUE TITLE
Исследовательская часть [26/09/18 - 03/10/18]

### ISSUE THREAD

**Issue by Shtandart** [Shtandart/Cource_Project#5]
> * [x]  Расписанные общие сведения 
> * [x]  Схема БД (или её более приемлемый вид)
> * [ ]  Перечень задач в процессе разработки 
> * [ ]  Обоснование выбора платформы для работы с БД

**Comment by Shtandart** [comment]
[ИЧ КомаровДС.docx](https://github.com/Shtandart/Cource_Project/files/2439944/default.docx)

**Comment by Shtandart** [comment]
Пока не полностью сформулировал задачи
И не нашёл подходящую информацию для выбора платформы для БД.( у меня в Excel расписание )

**Comment by wldmr-key** [comment]
2.1 Совершенно не описано, как система должна **получать** информацию. Безличный глагол "берутся" совершенно ни о чем. Тебе не кажется, что расписание групп и расписание преподавателей - это одно и то же?
2.2 Ты совершенно напрасно называешь представленную картинку концептуальной схемой - она ей не является. Понятно, почему? И здесь - тебе не кажется, что расписание групп и расписание преподавателей - это одно и то же? куда делась информация о событиях?
