### ISSUE TITLE
ИЧ [03/10/18 - 10/10/18]

### ISSUE THREAD

**Issue by Shtandart** [Shtandart/Cource_Project#6]
> > * [x]   Расписанные общие сведения
> > * [x]   Перечень задач в процессе разработки
> > * [x]   Обоснование выбора платформы для работы с БД

**Comment by Shtandart** [comment]
[ИЧ КомаровДС.docx](https://github.com/Shtandart/Cource_Project/files/2462012/default.docx)

**Comment by wldmr-key** [comment]
Общие сведения - по-прежнему, не описаны процессы, кто и что делает. Откуда в системе берется весь контент и что с ним происходит
Концептуальная схема - совсем не концептуальная схема - вспомни про er-диаграмму
задачи следует уже формулировать конкретно
